staging_events:
  create: |
    CREATE TABLE IF NOT EXISTS {schema}.{table}(
    artist varchar(256),
    auth varchar(256),
    firstname varchar(256),
    gender varchar(256),
    iteminsession int4,
    lastname varchar(256),
    length numeric(18,0),
    "level" varchar(256),
    location varchar(256),
    "method" varchar(256),
    page varchar(256),
    registration numeric(18,0),
    sessionid int4,
    song varchar(256),
    status int4,
    ts int8,
    useragent varchar(256),
    userid int4
    );
  copy: |
    COPY
        {schema}.{table} 
    FROM
        '{s3_path}'
    ACCESS_KEY_ID '{aws_key}'
    SECRET_ACCESS_KEY '{aws_secret}'
    REGION '{region}'
    json 's3://udacity-dend/log_json_path.json';




staging_songs:
  create: |
    CREATE TABLE IF NOT EXISTS {schema}.{table}(
    num_songs int4,
    artist_id varchar(256),
    artist_name varchar(256),
    artist_latitude numeric(18,0),
    artist_longitude numeric(18,0),
    artist_location varchar(256),
    song_id varchar(256),
    title varchar(256),
    duration numeric(18,0),
    "year" int4
    );
  copy: |
    COPY
        {schema}.{table}
    FROM
        '{s3_path}'
    ACCESS_KEY_ID '{aws_key}'
    SECRET_ACCESS_KEY '{aws_secret}'
    REGION '{region}'
    json 'auto';




songplays:
  create: |
    CREATE TABLE IF NOT EXISTS {schema}.{table} (
      playid varchar(32) NOT NULL,
      start_time timestamp NOT NULL,
      userid int4 NOT NULL,
      "level" varchar(256),
      songid varchar(256),
      artistid varchar(256),
      sessionid int4,
      location varchar(256),
      user_agent varchar(256),
      CONSTRAINT songplays_pkey PRIMARY KEY (playid)
    );
  
  insert: |
    INSERT INTO {schema}.{table} (
            playid,
            start_time,
            userid,
            level,
            songid,
            artistid,
            sessionid,
            location,
            user_agent
        )
        SELECT
                md5(events.sessionid || events.start_time) songplay_id,
                events.start_time, 
                events.userid, 
                events.level, 
                songs.song_id, 
                songs.artist_id, 
                events.sessionid, 
                events.location, 
                events.useragent
                FROM (SELECT TIMESTAMP 'epoch' + ts/1000 * interval '1 second' AS start_time, *
            FROM staging_events
            WHERE page='NextSong') events
            LEFT JOIN staging_songs songs
            ON events.song = songs.title
                AND events.artist = songs.artist_name
                AND events.length = songs.duration;




artists:
  create: |
    CREATE TABLE public.artists (
    artistid varchar(256) NOT NULL,
    name varchar(256),
    location varchar(256),
    lattitude numeric(18,0),
    longitude numeric(18,0)
    );





songs:
  create: |
    CREATE TABLE public.songs (
      songid varchar(256) NOT NULL,
      title varchar(256),
      artistid varchar(256),
      "year" int4,
      duration numeric(18,0),
      CONSTRAINT songs_pkey PRIMARY KEY (songid)
    );




time:
  create: |
    CREATE TABLE public."time" (
      start_time timestamp NOT NULL,
      "hour" int4,
      "day" int4,
      week int4,
      "month" varchar(256),
      "year" int4,
      weekday varchar(256),
      CONSTRAINT time_pkey PRIMARY KEY (start_time)
    );




users:
  create: |
    CREATE TABLE public.users (
      userid int4 NOT NULL,
      first_name varchar(256),
      last_name varchar(256),
      gender varchar(256),
      "level" varchar(256),
      CONSTRAINT users_pkey PRIMARY KEY (userid)
    );